name: ImmortalChat
version: 0.4.0
api-version: 1.13
main: com.sotmonstudios.java.ImmortalChat.Main
softdepend:
  - Vault
permissions:
  immortalchat.admin.togglechat:
    description: Gives permission to toggle chat.
    default: op
  immortalchat.bypass.chatdisable:
    description: Gives right to bypass disabled chat.
    default: op
  immortalcommand.commands:
    description: Displays command list.
    default: op