name: ServerChatPlus
version: 0.4.1
api-version: 1.13
main: org.magenpurp.onfimarist.ServerChatPlus.Main
softdepend:
  - Vault
permissions:
  scp.admin.togglechat:
    description: Gives permission to toggle chat.
    default: op
  scp.bypass.chatdisable:
    description: Gives right to bypass disabled chat.
    default: op
  scp.comamnds:
    description: Displays command list.
    default: op